### ISSUE TITLE
Client is not attempting reconnect

### ISSUE THREAD

**Issue by ethul** [thunks/thunk-disque#3]
The disque client looks to have reconnect functionality built in. However, I am having trouble getting the client to reconnect to the disque server.

My test scenario is that I first create a disque client and shortly afterwards shutdown the disque server. I expected that when I brought the server back up, the client would eventually reconnect. From my test, the client remains in the `ended` state and will not reconnect. If I trace through what the client is doing, it looks to be skipping the reconnect attempts because it [returns due to ended being true](https://github.com/thunks/thunk-disque/blob/05146eab91614f591414cf9d5f230cb9df52d186/lib/connection.js#L135).

Between 269076683ad1cb5f43730b2854413ea48df3433b...05146eab91614f591414cf9d5f230cb9df52d186 the `ended` property is now set to true when the socket's `close` event is fired due to the call to `tryRemove`. Any pointers for how to get this working would be very much appreciated.

**Comment by zensh** [comment]
Hi, disque server send a close signal to client when you shut down, it is not a  exception disconnect. In my application,  I listened `close` event and `error` event, when it occured, event handle throw some error , then application will be restarted.

**Comment by ethul** [comment]
Thanks for taking a look. Maybe I am not thinking about this the right way. However, even when I `kill -9 <disque-server-process-id>`, the [end handler](https://github.com/thunks/thunk-disque/blob/05146eab91614f591414cf9d5f230cb9df52d186/lib/connection.js#L123) is being called. Is this intended?

I am wondering how the client will attempt a reconnect once it is ended. Do you have an example of how this works? It would be very helpful.

Thanks.

**Comment by zensh** [comment]
@ethul I fixed this case, released v0.3.0. Here is example: https://github.com/thunks/thunk-disque/blob/master/examples/reconnect-forever.js

**Comment by ethul** [comment]
Great! And thank you for the example.
